### ISSUE TITLE
Implement WebRTC Data Channel in C#

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/TomasHubelbauer.WebRtcDataChannelsDotNet#2]
- [ ] Implement [WebRTC Data Channel](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13).
- [ ] Implement [SCTP](https://tools.ietf.org/html/rfc4960) protocol handling.
  - WebRTC uses SRTP for media and SCTP for data.
  - [Partial reliability SCTP extension is mandatory in WebRTC](https://tools.ietf.org/html/rfc3758).
  - [DCEP](https://tools.ietf.org/html/draft-ietf-rtcweb-data-protocol-08) is used for symmetric data channel.
- [ ] #9 Implement DTLS ([1.0](https://tools.ietf.org/html/rfc4347), [1.2](https://tools.ietf.org/html/rfc6347)) protocol handling.
  - WebRTC encapsulates SCTP in DTLS as described [here](https://tools.ietf.org/html/draft-ietf-tsvwg-sctp-dtls-encaps-07).
- [ ] #1 Implement UDP endpoint that will connect to the browser.
- [ ] #8 Implement SDP generation for exchange with the browser.
- [ ] #4 Implement [ICE/UDP](https://tools.ietf.org/html/rfc5245) NAT traversal solution.
  - [ ] #5 Gather local host candidate for testing on the same LAN.
  - [ ] #6 Implement STUN.
  - [ ] #6, #7 Implement TURN (implementing TURN would mean no alternative transport solution would be necessary for cases where two peers are behind symmetric NAT).

```
              +------+------+------+
              | DCEP | UTF-8|Binary|
              |      | data | data |
              +------+------+------+
              |        SCTP        |
+----------------------------------+
| STUN | SRTP |        DTLS        |
+----------------------------------+
|                ICE               |
+----------------------------------+
| UDP1 | UDP2 | UDP3 | ...         |
+----------------------------------+
```
##### Links
- http://www.slideshare.net/victorpascual/webrtc-datachannels-demystified
- http://www.codeproject.com/Articles/170415/How-to-Build-a-NET-Softphone-in-C-with-SIP-SDP-RTP
- http://www.codeproject.com/Articles/18977/How-to-use-the-managed-RTP-API-classes-in-NET-to-c
- https://github.com/conferencexp/conferencexp
- http://stackoverflow.com/questions/23845459/implementing-webrtc-data-channel-for-windows-applications
- https://github.com/ngraziano/SharpRTSP maybe related for inspiration.
- http://xsockets.net/docs/3/webrtc
- https://github.com/XSockets/XSockets.WebRTC
- http://opentools.homeip.net/webrtc
