### ISSUE TITLE
Implement ICE UDP candidate gathering in the UWP library

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/TomasHubelbauer.WebRtcDataChannelsDotNet#4]
[Here's a blog post about ICE gathering](http://blogs.technet.com/b/nexthop/archive/2009/04/22/how-communicator-uses-sdp-and-ice-to-establish-a-media-channel.aspx).

[Here's a SO answer outlining candidate types](http://stackoverflow.com/a/20499343/2715716).

Some links:
- http://www.voip-sip-sdk.com/p_380-how-to-manage-nat-traversal-using-csharp-voip.html
- https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment
- http://www.stunprotocol.org/StunTask.java

Sub-issues:
- [ ] #5 Gather the host candidate - the address of the local network interface(s).
- [ ] #6 Gather the server reflexive candidate - a translation of the local address into the public network through STUN.
- [ ] #7 Gather the relayed candidate - the TURN server address.

Peer reflexive candidate gathering is neglected, possibly revisit this in the future.
##### Useful resources
- [ICE: The ultimate way of beating NAT in SIP](http://www.slideshare.net/saghul/ice-4414037)
- [Anatomy of a WebRTC SDP(the candidate lines)](https://webrtchacks.com/sdp-anatomy/)
