### ISSUE TITLE
Implement local host UDP ICE candidate gathering

### ISSUE THREAD

**Issue by TomasHubelbauer** [TomasHubelbauer/TomasHubelbauer.WebRtcDataChannelsDotNet#5]
This should be done by iterating local network interfaces and looking for their address. Possibly this is somehow included in the UDP API endpoint provided by the UWP.

This candidate alone should be enough for local testing with a browser on the same machine as the Windows Universal application. Local host candidates from both the browser (with which to check!) and the UWA should match and enable the peer connection to go through.

The final candidate SDP line string should look like this:

```
a=candidate:2037708112 1 udp 2121206221 192.168.0.7 51478 typ host generation 0
```

According to [WebRTC SDP anatomy chart](https://webrtchacks.com/sdp-anatomy/), it breaks down to this:
- `2037708112` is a _foundation_, an identifier of the candidate. Has to do with [frozen candidates](http://tools.ietf.org/html/rfc5245#section-2.4).
- `1` is unknown to me at this point, probably some flag of the line type or something.
- `udp` is the protocol, which is always UDP for WebRTC Data Channel.
- `2121206221` is the candidate priority. [More in the RFC.](http://tools.ietf.org/html/rfc5245#section-4.1.2)
- `192.168.0.7` is the IP.
- `51478` is the port. [It is assigned randomly and is ephemeral, see RFC](http://tools.ietf.org/html/rfc5245#section-4.1.1.1).
- `typ host` means this is a local host candidate.
- `generation 0` means this candidate was gathered during the first ICE process and this number gets increased when renegotiating. I think.
##### Tasks
- [x] Gather inner network IP address from the DNS address list.
- [ ] Compute candidate foundation per the RFC.
- [ ] Compute candidate priority per the RFC.
- [ ] Establish infrastructure for dynamic port assignment - interoperability with UDP socket.
- [ ] Refactor to support multiple network interfaces, get rid of `Single`.
- [ ] Figure out what the `1` means and handle appropriately.
##### Implementation outline

``` cs
private string GetLocalHostUdpIceCandidateSdpLine()
{
  var foundation = 0; // TODO: http://tools.ietf.org/html/rfc5245#section-2.4
  var priority = 0; // TODO: http://tools.ietf.org/html/rfc5245#section-4.1.2
  var address = Dns.GetHostEntry(string.Empty) // Localhost.
    .AddressList
    .Where(ipAddress => ipAddress.AddressFamily == AddressFamily.InterNetwork)
    .SingleOrDefault();
  var port = 51000; // TODO: http://tools.ietf.org/html/rfc5245#section-4.1.1.1
  return $"a=candidate:{foundation} 1 udp {priority} {address} {port} typ host generation 0";
}
```
